# Generated by Django 4.2.27 on 2025-12-03 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('type', models.CharField(choices=[('monthly', 'Mensuel'), ('semester', 'Semestriel'), ('annual', 'Annuel'), ('custom', 'Personnalisé')], max_length=20, verbose_name='type')),
                ('period_start', models.DateField(verbose_name='début période')),
                ('period_end', models.DateField(verbose_name='fin période')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('content', models.JSONField(help_text='Données statistiques en JSON', verbose_name='contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='fichier PDF')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='archivé le')),
                ('year', models.PositiveIntegerField(verbose_name='année académique')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2, verbose_name='semestre')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='note finale')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='mots-clés')),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('achievements', models.TextField(blank=True, verbose_name='réalisations')),
                ('is_public', models.BooleanField(default=True, verbose_name='visible publiquement')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_projects', to=settings.AUTH_USER_MODEL, verbose_name='archivé par')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'projet archivé',
                'verbose_name_plural': 'projets archivés',
                'ordering': ['-year', '-archived_at'],
            },
        ),
    ]
