# Generated by Django 4.2.27 on 2025-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('assistant', 'Assistant'), ('maitre_assistant', 'Maître Assistant'), ('maitre_conference', 'Maître de Conférences'), ('professeur', 'Professeur')], help_text='Titre académique (obligatoire pour encadreurs)', max_length=50, verbose_name='titre académique'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_students',
            field=models.PositiveIntegerField(default=5, help_text="Nombre maximum d'étudiants pouvant être encadrés simultanément", verbose_name="nombre maximum d'étudiants"),
        ),
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, choices=[('GIT', 'Génie Informatique & Télécommunications'), ('GESI', 'Génie Électrique et Systèmes Intelligents'), ('GQHSEI', 'Génie de la Qualité Hygiène, Sécurité et Environnement Industriel'), ('GAM', 'Génie Automobile et Mécatronique'), ('GMP', 'Génie Maritime et Portuaire'), ('GP', 'Génie des Procédés'), ('GE', 'Génie Énergétique'), ('GM', 'Génie Mécanique'), ('GC', 'Génie Civil')], help_text="Filière d'appartenance (obligatoire pour étudiants, encadreurs et admins)", max_length=10, verbose_name='filière'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text='Ancien champ - utiliser academic_title', max_length=100, verbose_name='grade'),
        ),
    ]
