# Generated by Django 4.2.27 on 2025-12-07 15:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_academic_title_user_max_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, help_text='Format: xxGxxxxx (ex: 21G12345)', max_length=20, null=True, unique=True, validators=[users.models.validate_matricule], verbose_name='matricule'),
        ),
    ]
