# Generated by Django 4.2.27 on 2025-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_matricule_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry_level',
            field=models.CharField(blank=True, choices=[('1', 'Niveau 1 (Licence 1)'), ('3', 'Niveau 3 (Licence 3)')], help_text="Niveau auquel vous êtes entré à l'ENSPD", max_length=1, null=True, verbose_name="niveau d'entrée"),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('M2', 'Master 2')], help_text='Niveau actuel (M2 pour soutenance)', max_length=3, null=True, verbose_name='niveau actuel'),
        ),
    ]
