# Generated by Django 4.2.27 on 2025-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_supervisor_to_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('admin', 'Administration')], default='student', max_length=20, verbose_name='rôle'),
        ),
    ]
