# Generated by Django 4.2.27 on 2025-12-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filiere_admin',
            field=models.CharField(blank=True, choices=[('GIT', 'Génie Informatique & Télécommunications'), ('GESI', 'Génie Électrique et Systèmes Intelligents'), ('GQHSEI', 'Génie de la Qualité Hygiène, Sécurité et Environnement Industriel'), ('GAM', 'Génie Automobile et Mécatronique'), ('GMP', 'Génie Maritime et Portuaire'), ('GP', 'Génie des Procédés'), ('GE', 'Génie Énergétique'), ('GM', 'Génie Mécanique'), ('GC', 'Génie Civil')], help_text='Filière gérée (pour admin_filiere uniquement)', max_length=10, null=True, verbose_name='filière administrée'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('admin_filiere', 'Administrateur de Filière'), ('admin_general', 'Administrateur Général'), ('admin', 'Administration')], default='student', max_length=20, verbose_name='rôle'),
        ),
    ]
