# Generated by Django 4.2.27 on 2025-12-08 20:53

from django.db import migrations


def convert_admin_to_admin_general(apps, schema_editor):
    """Convertir tous les utilisateurs avec role='admin' en 'admin_general'"""
    User = apps.get_model('users', 'User')
    
    # Trouver tous les anciens admin
    old_admins = User.objects.filter(role='admin')
    count = old_admins.count()
    
    if count > 0:
        # Convertir en admin_general
        old_admins.update(role='admin_general')
        print(f"✅ {count} utilisateur(s) 'admin' converti(s) en 'admin_general'")
    else:
        print("ℹ️ Aucun utilisateur 'admin' à convertir")


def reverse_conversion(apps, schema_editor):
    """Fonction inverse (pour rollback)"""
    User = apps.get_model('users', 'User')
    User.objects.filter(role='admin_general').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_filiere_admin_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(convert_admin_to_admin_general, reverse_conversion),
    ]
