# Generated by Django 4.2.27 on 2025-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_convert_old_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('admin_filiere', 'Administrateur de Filière'), ('admin_general', 'Administrateur Général')], default='student', max_length=20, verbose_name='rôle'),
        ),
    ]
