# Generated by Django 4.2.27 on 2025-12-03 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0002_alter_subject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='titre du projet')),
                ('description', models.TextField(verbose_name='description')),
                ('objectives', models.TextField(verbose_name='objectifs')),
                ('methodology', models.TextField(blank=True, verbose_name='méthodologie')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='technologies utilisées')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('submitted', 'Soumis'), ('under_review', 'En révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], default='in_progress', max_length=20, verbose_name='statut')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="pourcentage d'avancement")),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='date de fin prévue')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='date de fin réelle')),
                ('repository_url', models.URLField(blank=True, verbose_name='URL du dépôt')),
                ('documentation_url', models.URLField(blank=True, verbose_name='URL de la documentation')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='projects/reports/', verbose_name='rapport final')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='projects/presentations/', verbose_name='présentation')),
                ('supervisor_notes', models.TextField(blank=True, verbose_name="notes de l'encadreur")),
                ('supervisor_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="note de l'encadreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='subjects.assignment', verbose_name='affectation')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('delayed', 'En retard')], default='pending', max_length=20, verbose_name='statut')),
                ('due_date', models.DateField(verbose_name="date d'échéance")),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='date de complétion')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('validated_by_supervisor', models.BooleanField(default=False, verbose_name='validé')),
                ('validation_date', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'jalon',
                'verbose_name_plural': 'jalons',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('report', 'Rapport'), ('code', 'Code source'), ('documentation', 'Documentation'), ('presentation', 'Présentation'), ('video', 'Vidéo'), ('other', 'Autre')], default='report', max_length=20, verbose_name='type')),
                ('file', models.FileField(upload_to='projects/deliverables/', verbose_name='fichier')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumis'), ('reviewed', 'Révisé'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='soumis le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='révisé le')),
                ('review_comments', models.TextField(blank=True, verbose_name='commentaires')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='projects.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deliverables', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'livrable',
                'verbose_name_plural': 'livrables',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('is_private', models.BooleanField(default=False, verbose_name='privé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['created_at'],
            },
        ),
    ]
