# Generated by Django 4.2.27 on 2025-12-04 23:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('awaiting_kickoff', 'En attente de cadrage'), ('in_progress', 'En cours'), ('submitted', 'Soumis'), ('under_review', 'En révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], default='in_progress', max_length=20, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kickoff', 'Réunion de cadrage'), ('follow_up', 'Réunion de suivi'), ('milestone_review', 'Revue de jalon'), ('final_review', 'Revue finale'), ('emergency', "Réunion d'urgence")], default='follow_up', max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, help_text='Ordre du jour / Sujets à discuter', verbose_name='description')),
                ('scheduled_date', models.DateTimeField(verbose_name='date prévue')),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)], verbose_name='durée (minutes)')),
                ('location', models.CharField(blank=True, help_text='Bureau, salle, ou lien visioconférence', max_length=200, verbose_name='lieu')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('completed', 'Complétée'), ('cancelled', 'Annulée'), ('rescheduled', 'Reportée')], default='scheduled', max_length=20, verbose_name='statut')),
                ('minutes', models.TextField(blank=True, help_text='Résumé de la réunion', verbose_name='compte-rendu')),
                ('topics_discussed', models.TextField(blank=True, verbose_name='points discutés')),
                ('decisions_made', models.TextField(blank=True, verbose_name='décisions prises')),
                ('action_items', models.TextField(blank=True, help_text='Actions décidées avec responsables', verbose_name='actions à réaliser')),
                ('student_notes', models.TextField(blank=True, verbose_name="notes de l'étudiant")),
                ('supervisor_notes', models.TextField(blank=True, verbose_name="notes de l'encadreur")),
                ('next_meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='date de la prochaine réunion')),
                ('student_attended', models.BooleanField(default=True, verbose_name='étudiant présent')),
                ('supervisor_attended', models.BooleanField(default=True, verbose_name='encadreur présent')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='meetings/attachments/', verbose_name='pièces jointes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complétée le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'réunion',
                'verbose_name_plural': 'réunions',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['project', 'status'], name='projects_me_project_eee87e_idx'), models.Index(fields=['scheduled_date'], name='projects_me_schedul_e258a7_idx')],
            },
        ),
    ]
