# Generated by Django 4.2.27 on 2025-12-04 23:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text="Date de l'activité", verbose_name='date')),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text="Nombre d'heures travaillées", max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='durée (heures)')),
                ('activities', models.TextField(help_text='Décrivez en détail ce qui a été fait', verbose_name='activités réalisées')),
                ('achievements', models.TextField(blank=True, help_text='Objectifs atteints, livrables produits', verbose_name='réalisations/résultats')),
                ('difficulties', models.TextField(blank=True, help_text='Problèmes, blocages, questions', verbose_name='difficultés rencontrées')),
                ('next_steps', models.TextField(blank=True, help_text='Ce qui est prévu pour la prochaine session', verbose_name='prochaines étapes')),
                ('resources_used', models.TextField(blank=True, help_text='Documentation, tutoriels, outils utilisés', verbose_name='ressources utilisées')),
                ('is_visible_to_supervisor', models.BooleanField(default=True, help_text="L'encadreur peut voir cette entrée", verbose_name="visible par l'encadreur")),
                ('supervisor_feedback', models.TextField(blank=True, verbose_name="commentaires de l'encadreur")),
                ('supervisor_read_at', models.DateTimeField(blank=True, null=True, verbose_name="lu par l'encadreur le")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'entrée du journal de bord',
                'verbose_name_plural': 'journal de bord',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
