# Generated by Django 4.2.27 on 2025-12-07 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='projects.project', verbose_name='Projet')),
                ('student1', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_student1', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant 1 (principal)')),
                ('student2', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_student2', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant 2 (binôme)')),
            ],
            options={
                'verbose_name': 'Équipe de projet',
                'verbose_name_plural': 'Équipes de projet',
            },
        ),
    ]
