# Generated by Django 4.2.27 on 2025-12-07 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Format: 2025-2026', max_length=9, unique=True, verbose_name='année académique')),
                ('start_date', models.DateField(help_text="Date de début de l'année académique", verbose_name='date de début')),
                ('end_date', models.DateField(help_text="Date de fin de l'année académique", verbose_name='date de fin')),
                ('thesis_submission_deadline', models.DateField(help_text='Date limite pour la soumission des mémoires de PFE', verbose_name='date limite de dépôt des mémoires')),
                ('is_active', models.BooleanField(default=False, help_text='Une seule année peut être active à la fois', verbose_name='année active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'année académique',
                'verbose_name_plural': 'années académiques',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='thesis_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'approbation du mémoire"),
        ),
        migrations.AddField(
            model_name='project',
            name='thesis_approved_by_supervisor',
            field=models.BooleanField(default=False, help_text="L'encadreur doit approuver le mémoire avant distribution au jury", verbose_name="mémoire approuvé par l'encadreur"),
        ),
        migrations.AddField(
            model_name='project',
            name='thesis_distributed_to_jury',
            field=models.BooleanField(default=False, verbose_name='mémoire distribué au jury'),
        ),
        migrations.AddField(
            model_name='project',
            name='thesis_distribution_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de distribution au jury'),
        ),
        migrations.AddField(
            model_name='project',
            name='thesis_file',
            field=models.FileField(blank=True, help_text='Fichier PDF du mémoire final', null=True, upload_to='projects/thesis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='mémoire de PFE'),
        ),
        migrations.AddField(
            model_name='project',
            name='thesis_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de soumission du mémoire'),
        ),
        migrations.AddField(
            model_name='project',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.academicyear', verbose_name='année académique'),
        ),
    ]
