# Generated by Django 4.2.27 on 2025-12-03 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='heure')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='durée (minutes)')),
                ('room', models.CharField(max_length=100, verbose_name='salle')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='bâtiment')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rescheduled', 'Reportée')], default='scheduled', max_length=20, verbose_name='statut')),
                ('presentation_duration', models.PositiveIntegerField(default=15, verbose_name='durée présentation (min)')),
                ('questions_duration', models.PositiveIntegerField(default=15, verbose_name='durée questions (min)')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note finale')),
                ('jury_comments', models.TextField(blank=True, verbose_name='commentaires du jury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'soutenance',
                'verbose_name_plural': 'soutenances',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='DefenseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='qualité présentation')),
                ('content_mastery', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='maîtrise du contenu')),
                ('technical_skills', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='compétences techniques')),
                ('communication', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='communication')),
                ('answers_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='qualité des réponses')),
                ('overall_impression', models.TextField(blank=True, verbose_name='impression générale')),
                ('strengths', models.TextField(blank=True, verbose_name='points forts')),
                ('weaknesses', models.TextField(blank=True, verbose_name='points à améliorer')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommandations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='defenses.defense', verbose_name='soutenance')),
            ],
            options={
                'verbose_name': 'évaluation de soutenance',
                'verbose_name_plural': 'évaluations de soutenance',
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'Président'), ('examiner', 'Examinateur'), ('supervisor', 'Encadreur')], max_length=20, verbose_name='rôle')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note')),
                ('comments', models.TextField(blank=True, verbose_name='commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members', to='defenses.defense', verbose_name='soutenance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL, verbose_name='membre')),
            ],
            options={
                'verbose_name': 'membre du jury',
                'verbose_name_plural': 'membres du jury',
                'unique_together': {('defense', 'user')},
            },
        ),
    ]
