# Generated by Django 4.2.27 on 2025-12-03 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField(blank=True, null=True, verbose_name='date proposée')),
                ('proposed_time', models.TimeField(blank=True, null=True, verbose_name='heure proposée')),
                ('proposed_location', models.CharField(blank=True, max_length=200, verbose_name='lieu proposé')),
                ('reason', models.TextField(verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut')),
                ('review_comment', models.TextField(blank=True, verbose_name='commentaire de révision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='examiné le')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='defenses.defense', verbose_name='soutenance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='demandé par')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defense_changes', to=settings.AUTH_USER_MODEL, verbose_name='examiné par')),
            ],
            options={
                'verbose_name': 'demande de modification de soutenance',
                'verbose_name_plural': 'demandes de modification de soutenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
