# Generated by Django 4.2.27 on 2025-12-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defenses', '0002_defensechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom de la salle')),
                ('building', models.CharField(max_length=100, verbose_name='bâtiment')),
                ('capacity', models.PositiveIntegerField(help_text='Nombre de places assises', verbose_name='capacité')),
                ('equipment', models.TextField(blank=True, help_text='Ex: Projecteur, tableau blanc, son', verbose_name='équipement disponible')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.AddField(
            model_name='jurymember',
            name='is_president',
            field=models.BooleanField(default=False, help_text='Seuls les Professeurs peuvent être présidents', verbose_name='est président'),
        ),
        migrations.AlterField(
            model_name='defense',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='bâtiment (ancien)'),
        ),
        migrations.AlterField(
            model_name='defense',
            name='room',
            field=models.CharField(blank=True, max_length=100, verbose_name='salle (ancien)'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='role',
            field=models.CharField(choices=[('president', 'Président'), ('examiner', 'Examinateur'), ('supervisor', 'Encadreur'), ('guest', 'Invité')], max_length=20, verbose_name='rôle'),
        ),
        migrations.AddField(
            model_name='defense',
            name='room_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defenses', to='defenses.room', verbose_name='salle'),
        ),
    ]
