# Generated by Django 4.2.27 on 2025-12-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defenses', '0002_add_defense_jury'),
        ('defenses', '0003_room_jurymember_is_president_alter_defense_building_and_more'),
    ]

    operations = [
    ]
