# Generated by Django 4.2.27 on 2025-12-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defenses', '0004_merge_20251207_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['filiere', 'building', 'name'], 'verbose_name': 'salle', 'verbose_name_plural': 'salles'},
        ),
        migrations.AddField(
            model_name='room',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'Génie Informatique & Télécommunications'), ('GESI', 'Génie Électrique et Systèmes Intelligents'), ('GQHSEI', 'Génie de la Qualité Hygiène, Sécurité et Environnement Industriel'), ('GAM', 'Génie Automobile et Mécatronique'), ('GMP', 'Génie Maritime et Portuaire'), ('GP', 'Génie des Procédés'), ('GE', 'Génie Énergétique'), ('GM', 'Génie Mécanique'), ('GC', 'Génie Civil'), ('GENERAL', 'Usage Général')], default='GENERAL', help_text='Filière prioritaire pour cette salle', max_length=10, verbose_name='filière'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Ex: Amphi A, Salle 101', max_length=100, verbose_name='nom de la salle'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'building')},
        ),
    ]
