# Generated by Django 4.2.27 on 2025-12-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defenses', '0005_alter_room_options_room_filiere_alter_room_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor', 'room_number'], 'verbose_name': 'salle', 'verbose_name_plural': 'salles'},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('1', 'Étage 1'), ('2', 'Étage 2')], default='1', help_text='Étage 1 ou 2 uniquement', max_length=1, verbose_name='étage'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='01', help_text='Numéro entre 01 et 34', max_length=2, verbose_name='numéro de salle'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(choices=[('BP', 'Bloc Pédagogique'), ('BS', 'Bloc des Spécialités')], default='BP', help_text='BP = Bloc Pédagogique, BS = Bloc des Spécialités', max_length=2, verbose_name='bâtiment'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(editable=False, help_text='Généré automatiquement: yyBPx ou yyBSx', max_length=10, unique=True, verbose_name='nom de la salle'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'building')},
        ),
    ]
