# Generated by Django 4.2.27 on 2025-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defenses', '0006_room_nomenclature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'salle', 'verbose_name_plural': 'salles'},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('17BS1', 'Salle 17BS1'), ('16BS1', 'Salle 16BS1'), ('15BS1', 'Salle 15BS1'), ('14BS1', 'Salle 14BS1'), ('13BS1', 'Salle 13BS1'), ('12BS1', 'Salle 12BS1'), ('10BS1', 'Salle 10BS1'), ('30BS2', 'Salle 30BS2'), ('31BS2', 'Salle 31BS2'), ('32BS2', 'Salle 32BS2'), ('33BS2', 'Salle 33BS2'), ('34BS2', 'Salle 34BS2'), ('29BS2', 'Salle 29BS2'), ('27BS2', 'Salle 27BS2'), ('26BS2', 'Salle 26BS2'), ('24BS2', 'Salle 24BS2'), ('25BS2', 'Salle 25BS2'), ('23BS2', 'Salle 23BS2'), ('22BS2', 'Salle 22BS2'), ('21BS2', 'Salle 21BS2'), ('20BS2', 'Salle 20BS2'), ('19BS2', 'Salle 19BS2'), ('18BS2', 'Salle 18BS2'), ('17BP1', 'Salle 17BP1'), ('16BP1', 'Salle 16BP1'), ('15BP1', 'Salle 15BP1'), ('14BP1', 'Salle 14BP1'), ('13BP1', 'Salle 13BP1'), ('12BP1', 'Salle 12BP1'), ('10BP1', 'Salle 10BP1'), ('30BP2', 'Salle 30BP2'), ('31BP2', 'Salle 31BP2'), ('32BP2', 'Salle 32BP2'), ('33BP2', 'Salle 33BP2'), ('34BP2', 'Salle 34BP2'), ('29BP2', 'Salle 29BP2'), ('27BP2', 'Salle 27BP2'), ('26BP2', 'Salle 26BP2'), ('24BP2', 'Salle 24BP2'), ('25BP2', 'Salle 25BP2'), ('23BP2', 'Salle 23BP2'), ('22BP2', 'Salle 22BP2'), ('21BP2', 'Salle 21BP2'), ('20BP2', 'Salle 20BP2'), ('19BP2', 'Salle 19BP2'), ('18BP2', 'Salle 18BP2')], help_text='Sélectionnez une salle dans la liste', max_length=10, unique=True, verbose_name='nom de la salle'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
