# Generated by Django 4.2.27 on 2025-12-03 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_letter', models.TextField(help_text='Expliquez pourquoi vous souhaitez travailler sur ce sujet', verbose_name='lettre de motivation')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='applications/cv/', verbose_name='CV')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='pending', max_length=20, verbose_name='statut')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = priorité maximale, 5 = priorité minimale', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='priorité')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='évalué le')),
                ('review_notes', models.TextField(blank=True, verbose_name="notes d'évaluation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='évalué par')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(help_text='Description détaillée du sujet', verbose_name='description')),
                ('objectives', models.TextField(blank=True, help_text='Objectifs du projet', verbose_name='objectifs')),
                ('prerequisites', models.TextField(blank=True, help_text='Connaissances requises', verbose_name='prérequis')),
                ('keywords', models.CharField(blank=True, help_text='Séparer par des virgules', max_length=200, verbose_name='mots-clés')),
                ('domain', models.CharField(choices=[('informatique', 'Informatique'), ('reseaux', 'Réseaux et Télécommunications'), ('securite', 'Sécurité Informatique'), ('ia', 'Intelligence Artificielle'), ('web', 'Développement Web'), ('mobile', 'Développement Mobile'), ('data', 'Science des Données'), ('systemes', 'Systèmes Embarqués'), ('autre', 'Autre')], default='informatique', max_length=50, verbose_name='domaine')),
                ('type', models.CharField(choices=[('research', 'Recherche'), ('development', 'Développement'), ('mixed', 'Mixte')], default='mixed', max_length=20, verbose_name='type')),
                ('level', models.CharField(choices=[('L3', 'Licence 3'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], max_length=3, verbose_name='niveau')),
                ('max_students', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name="nombre maximum d'étudiants")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('assigned', 'Attribué'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='disponible à partir du')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name="disponible jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervised_subjects', to=settings.AUTH_USER_MODEL, verbose_name='co-encadreur')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_subjects', to=settings.AUTH_USER_MODEL, verbose_name='encadreur')),
            ],
            options={
                'verbose_name': 'sujet',
                'verbose_name_plural': 'sujets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='date de fin prévue')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='subjects.application', verbose_name='candidature')),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='affecté par')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subjects.subject', verbose_name='sujet')),
            ],
            options={
                'verbose_name': 'affectation',
                'verbose_name_plural': 'affectations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='subjects.subject', verbose_name='sujet'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status', 'level'], name='subjects_su_status_194ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['domain'], name='subjects_su_domain_4309de_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='subjects_as_status_c0c3ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('student',)},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'priority'], name='subjects_ap_status_13ea78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('subject', 'student')},
        ),
    ]
