# Generated by Django 4.2.27 on 2025-12-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('assigned', 'Attribué'), ('archived', 'Archivé')], default='published', max_length=20, verbose_name='statut'),
        ),
    ]
