# Generated by Django 4.2.27 on 2025-12-04 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0002_alter_subject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de votre projet proposé', max_length=200, verbose_name='titre du projet')),
                ('description', models.TextField(help_text='Description détaillée de votre idée de projet', verbose_name='description')),
                ('objectives', models.TextField(help_text='Quels sont les objectifs de ce projet ?', verbose_name='objectifs')),
                ('methodology', models.TextField(blank=True, help_text='Comment comptez-vous réaliser ce projet ?', verbose_name='méthodologie envisagée')),
                ('technologies', models.CharField(blank=True, help_text="Technologies que vous prévoyez d'utiliser", max_length=500, verbose_name='technologies')),
                ('domain', models.CharField(choices=[('informatique', 'Informatique'), ('reseaux', 'Réseaux et Télécommunications'), ('securite', 'Sécurité Informatique'), ('ia', 'Intelligence Artificielle'), ('web', 'Développement Web'), ('mobile', 'Développement Mobile'), ('data', 'Science des Données'), ('systemes', 'Systèmes Embarqués'), ('autre', 'Autre')], default='informatique', max_length=50, verbose_name='domaine')),
                ('type', models.CharField(choices=[('research', 'Recherche'), ('development', 'Développement'), ('mixed', 'Mixte')], default='development', max_length=20, verbose_name='type')),
                ('supervisor_justification', models.TextField(blank=True, help_text='Pourquoi avez-vous choisi ces encadreurs ?', verbose_name='justification du choix des encadreurs')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='pending', max_length=20, verbose_name='statut')),
                ('supervisor_comments', models.TextField(blank=True, verbose_name="commentaires de l'encadreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de révision')),
                ('accepted_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_proposals', to=settings.AUTH_USER_MODEL, verbose_name='acceptée par')),
                ('preferred_supervisor_1', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_choice_1', to=settings.AUTH_USER_MODEL, verbose_name="1er choix d'encadreur")),
                ('preferred_supervisor_2', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_choice_2', to=settings.AUTH_USER_MODEL, verbose_name="2ème choix d'encadreur")),
                ('preferred_supervisor_3', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_choice_3', to=settings.AUTH_USER_MODEL, verbose_name="3ème choix d'encadreur")),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
            ],
            options={
                'verbose_name': "proposition d'étudiant",
                'verbose_name_plural': "propositions d'étudiants",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'student'], name='subjects_st_status_0a1bc6_idx'), models.Index(fields=['status', 'preferred_supervisor_1'], name='subjects_st_status_6ff255_idx')],
            },
        ),
    ]
