# Generated by Django 4.2.27 on 2025-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_studentproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproposal',
            name='is_interdisciplinary',
            field=models.BooleanField(default=False, help_text='Mon projet concerne plusieurs filières', verbose_name='projet interdisciplinaire'),
        ),
        migrations.AddField(
            model_name='studentproposal',
            name='related_filieres',
            field=models.JSONField(blank=True, default=list, help_text='Autres filières concernées par ce projet', verbose_name='filières associées'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_interdisciplinary',
            field=models.BooleanField(default=False, help_text='Cochez si ce projet implique plusieurs filières', verbose_name='projet interdisciplinaire'),
        ),
        migrations.AddField(
            model_name='subject',
            name='primary_filiere',
            field=models.CharField(blank=True, choices=[], max_length=10, verbose_name='filière principale'),
        ),
        migrations.AddField(
            model_name='subject',
            name='related_filieres',
            field=models.JSONField(blank=True, default=list, help_text='Liste des autres filières concernées par le projet', verbose_name='filières associées'),
        ),
    ]
