# Generated by Django 4.2.27 on 2025-12-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_studentproposal_is_interdisciplinary_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='subjects_su_domain_4309de_idx',
        ),
        migrations.RemoveField(
            model_name='studentproposal',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='primary_filiere',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='related_filieres',
        ),
        migrations.AddField(
            model_name='studentproposal',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'Génie Informatique & Télécommunications'), ('GESI', 'Génie Électrique et Systèmes Intelligents'), ('GQHSEI', 'Génie de la Qualité Hygiène, Sécurité et Environnement Industriel'), ('GAM', 'Génie Automobile et Mécatronique'), ('GMP', 'Génie Maritime et Portuaire'), ('GP', 'Génie des Procédés'), ('GE', 'Génie Énergétique'), ('GM', 'Génie Mécanique'), ('GC', 'Génie Civil')], default='GIT', help_text='Filière de votre projet', max_length=10, verbose_name='filière'),
        ),
        migrations.AddField(
            model_name='subject',
            name='additional_filieres',
            field=models.JSONField(blank=True, default=list, help_text='Autres filières pouvant candidater (projets interdisciplinaires)', verbose_name='filières additionnelles'),
        ),
        migrations.AddField(
            model_name='subject',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'Génie Informatique & Télécommunications'), ('GESI', 'Génie Électrique et Systèmes Intelligents'), ('GQHSEI', 'Génie de la Qualité Hygiène, Sécurité et Environnement Industriel'), ('GAM', 'Génie Automobile et Mécatronique'), ('GMP', 'Génie Maritime et Portuaire'), ('GP', 'Génie des Procédés'), ('GE', 'Génie Énergétique'), ('GM', 'Génie Mécanique'), ('GC', 'Génie Civil')], default='GIT', help_text='Filière principale du sujet', max_length=10, verbose_name='filière'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['filiere'], name='subjects_su_filiere_ff1caa_idx'),
        ),
    ]
