# Generated by Django 4.2.27 on 2025-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_rename_domain_to_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='allows_pair',
            field=models.BooleanField(default=False, help_text='Le sujet peut être réalisé par 2 étudiants', verbose_name='Accepte un binôme'),
        ),
    ]
